[tox]
env_list = lint, py312

[testenv]
description = Run test suite with pytest
dependency_groups = dev
commands =
    pytest

[testenv:lint]
description = Run static checks with ruff
dependency_groups = dev
commands =
    ruff check .

[testenv:.pkg]
dependency_groups = dev
