[tox]
env_list = lint, py312

[testenv]
description = Run test suite with pytest
package = skip
dependency_groups = dev
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest

[testenv:lint]
description = Run static checks with ruff
package = skip
dependency_groups = dev
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    ruff check .
